Repository scoutapp/scout-apm-php-ext, pull requests merged in 2019-09, with the labels that each got.

#26 Record arguments from functions
  .gitignore
  README.md
  config.m4
  example.php
  tests/001-check-ext-loaded.phpt
  tests/002-file_get_contents.phpt
  tests/004-namespaced-fgc-is-not-logged.phpt
  zend_scoutapm.c
  zend_scoutapm.h
Labels: WIP

#31 Prepare for PECL releases
  .circleci/config.yml
  CMakeLists.txt
  CREDITS
  EXPERIMENTAL
  README.md
  config.m4
  package.xml
  tests/001-check-ext-loaded.phpt
  zend_scoutapm.c
  zend_scoutapm.h
Labels: enhancement

#34 fix c89 standard
  zend_scoutapm.c
Labels: bug

#35 Added CircleCI build badge to README.md to easily reference build state
  README.md
Labels: documentation, enhancement

#32 Release 0.0.4 - version fixes, compatibility across versions
  README.md
  package.xml
  tests/011-pdo-exec.phpt
  zend_scoutapm.c
  zend_scoutapm.h
Labels: bug
