Repository scoutapp/scout-apm-php-ext, pull requests merged in 2019-11, with the labels that each got.

#42 Overload function arguments better
  CMakeLists.txt
  config.m4
  package.xml
  scout_curl_wrapper.c
  scout_extern.h
  scout_file_wrapper.c
  scout_pdo_wrapper.c
  tests/009-curl_exec.phpt
  tests/010-fwrite-fread-fopen.phpt
  tests/010-fwrite-fread-tmpfile.phpt
  tests/011-pdostatement-execute-pdo-prepare.phpt
  zend_scoutapm.c
  zend_scoutapm.h
Labels: enhancement

#43 Tweaks to PR #42
  scout_file_wrapper.c
  tests/009-curl_exec.phpt
Labels: enhancement

#44 Deal with handler mapping or definition-related crashes
  scout_curl_wrapper.c
  scout_file_wrapper.c
  scout_pdo_wrapper.c
  zend_scoutapm.c
  zend_scoutapm.h
Labels: bug

#45 Updates in prep for a 1.0.0 release
  README.md
  package.xml
  zend_scoutapm.h
Labels: WIP, enhancement

#48 Fixes segfault that happens when arguments are looped over too high
  package.xml
  tests/bug-47.phpt
  zend_scoutapm.c
Labels: bug

#50 Fix fopen throwing exception when file does not exist
  package.xml
  scout_file_wrapper.c
  tests/bug-49.phpt
Labels: bug

#51 Removed notice emitted when ScoutAPM could not determine arguments for a call
  package.xml
  tests/010-fwrite-fread-tmpfile.phpt
  tests/bug-47.phpt
  zend_scoutapm.c
Labels: enhancement

#52 Bump version and date for 1.0.1 release
  package.xml
  zend_scoutapm.h
Labels: enhancement

#54 Optionally compile with curl support
  .circleci/config.yml
  config.m4
  package.xml
  scout_curl_wrapper.c
  tests/009-curl_exec.phpt
  zend_scoutapm.c
  zend_scoutapm.h
Labels: enhancement

#56 Fixing bug #55 - crash when running doctrine/migrations tests
  tests/bug-55.phpt
  zend_scoutapm.c
Labels: bug

#57 Release PR for 1.0.2
  .circleci/config.yml
  package.xml
  zend_scoutapm.h
Labels: enhancement

#58 Issue curl
  .gitignore
  config.m4
  zend_scoutapm.c
Labels: enhancement
